language: android
os:
 - linux
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - emulator -avd test2 -no-audio -no-window &
  - android-wait-for-emulator
  - git clone https://github.com/appetizerio/replaykit
  - export APPETIZER_TOOLKIT=replaykit
  - export DEVICE_SN1=$(adb devices | awk 'NR==2 {print $1}')
  - export DEVICE_SN2=$(adb devices | awk 'NR==3 {print $1}')
script:
  - ./gradlew check
