language: java
os:
 - linux
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - git clone git@github.com:appetizerio/replaykit.git
  - export APPETIZER_TOOLKIT=replaykit
