language: android
os:
 - linux
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - git clone https://github.com/appetizerio/replaykit
  - export APPETIZER_TOOLKIT=replaykit
script:
  - ./gradlew check
